#-*- coding: utf-8 -*-


TextWidget: # ルートに追加

<TextWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        
        # ラベル
        Label:
            id: label1
            font_size: 68
            text: root.text

        BoxLayout:
            Button:
                id: button1
                text: "morning"
                font_size: 68
                on_press: root.buttonClicked()  # ボタンをクリックした時

            Button:
                id: button2
                text: "day"
                font_size: 68
                on_press: root.buttonClicked2()  # ボタンをクリックした時

            Button:
                id: button3
                text: "night"
                font_size: 68
                on_press: root.buttonClicked3()  # ボタンをクリックした時